version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: bot_db
    ports:
      - 27017:27017
    volumes:
    - ./db:/data/db

  bot:
    depends_on:
      - mongo
    environment:
      - ENV=dev
    build:
      args:
        CONFIG: config.json
        ENV: dev
      context: .
      dockerfile: ./telegram/Dockerfile
    container_name: bot
    volumes:
      - ./logs:/app/logs
    hostname: bot

  admin:
    depends_on:
        - mongo
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
      MONGO_DB: bot_db
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    build:
      args:
          ENV: dev
      context: ./admin
    volumes:
      - ./admin/bot/:/app/bot/
    container_name: admin
    ports:
      - 8000:8000
    restart: always
