# Generated by Django 4.0.1 on 2022-01-18 19:48

import uuid

import django.db.models.deletion
import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                (
                    'description',
                    models.TextField(blank=True, default=None, verbose_name='Описание'),
                ),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Gymnastic',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('value', models.CharField(max_length=50, verbose_name='Повторения')),
                (
                    'exercise',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='bot.exercise',
                        verbose_name='Упражнение',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                (
                    'rounds_amount',
                    models.PositiveIntegerField(default=3, verbose_name='Кол-во раундов'),
                ),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                (
                    'gymnastics',
                    djongo.models.fields.ArrayReferenceField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='bot.gymnastic',
                        verbose_name='Задания',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Сет',
                'verbose_name_plural': 'Сеты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('telegram_id', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('birth_date', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('activated', models.BooleanField(default=False, verbose_name='Активированный')),
                (
                    'sex',
                    models.CharField(
                        blank=True,
                        choices=[('M', 'Мужской'), ('F', 'Женский')],
                        max_length=1,
                        null=True,
                        verbose_name='Пол',
                    ),
                ),
                (
                    'groups',
                    djongo.models.fields.ArrayReferenceField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='bot.group',
                        verbose_name='Группы',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'description',
                    models.TextField(blank=True, default=None, verbose_name='Описание'),
                ),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('week_start_date', models.DateField(verbose_name='Дата начала недели')),
                (
                    'min_rm_percent',
                    models.PositiveIntegerField(verbose_name='Мин. процент от макс. веса'),
                ),
                (
                    'max_rm_percent',
                    models.PositiveIntegerField(verbose_name='Макс. процент от макс. веса'),
                ),
                (
                    'groups',
                    djongo.models.fields.ArrayReferenceField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='bot.group',
                        verbose_name='Группы',
                    ),
                ),
                (
                    'sets',
                    djongo.models.fields.ArrayReferenceField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='bot.set',
                        verbose_name='Сеты',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ('week_start_date',),
            },
        ),
    ]
