# Generated by Django 4.0.1 on 2022-01-11 18:45

import django.db.models.deletion
import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gymnastic',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('description', models.TextField(blank=True)),
                ('value', models.CharField(blank=True, max_length=50)),
                (
                    'exercise',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='bot.exercise'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('description', models.TextField(blank=True)),
                ('rounds_amount', models.PositiveIntegerField()),
                (
                    'gymnastics',
                    djongo.models.fields.ArrayReferenceField(
                        on_delete=django.db.models.deletion.CASCADE, to='bot.gymnastic'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('telegram_id', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('second_name', models.CharField(max_length=32)),
                ('birth_date', models.DateField(blank=True)),
                ('activated', models.BooleanField(default=False)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                (
                    'groups',
                    djongo.models.fields.ArrayReferenceField(
                        on_delete=django.db.models.deletion.CASCADE, to='bot.group'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('description', models.TextField(blank=True, default=None)),
                ('order', models.PositiveIntegerField(default=3)),
                ('week_start_date', models.DateField()),
                ('min_rm_percent', models.PositiveIntegerField()),
                ('max_rm_percent', models.PositiveIntegerField()),
                (
                    'groups',
                    djongo.models.fields.ArrayReferenceField(
                        on_delete=django.db.models.deletion.CASCADE, to='bot.group'
                    ),
                ),
                (
                    'sets',
                    djongo.models.fields.ArrayReferenceField(
                        on_delete=django.db.models.deletion.CASCADE, to='bot.set'
                    ),
                ),
            ],
        ),
    ]
