# Generated by Django 4.0.1 on 2022-01-09 20:39

import bot.models
import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None)),
                ('link', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Gymnastic',
            fields=[
                ('gymnastic_id', models.IntegerField(primary_key=True, serialize=False)),
                (
                    'exercise',
                    djongo.models.fields.EmbeddedField(model_container=bot.models.Exercise),
                ),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('set_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('rounds_amount', models.PositiveIntegerField()),
                (
                    'gymnastics',
                    djongo.models.fields.ArrayField(model_container=bot.models.Gymnastic),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default=None)),
                ('training_type', models.CharField(max_length=40)),
                ('index', models.PositiveIntegerField()),
                ('week_start_date', models.DateField()),
                ('min_rm_percent', models.PositiveIntegerField()),
                ('max_rm_percent', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('telegram_id', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField(null=True)),
                ('activated', models.BooleanField(default=False)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('week_id', models.IntegerField(primary_key=True, serialize=False)),
                ('week_start_date', models.DateField()),
                ('trainings', djongo.models.fields.ArrayField(model_container=bot.models.Training)),
            ],
        ),
    ]
