# Generated by Django 4.0.1 on 2022-02-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymnastic',
            name='value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Повторения'),
        ),
        migrations.AlterField(
            model_name='set',
            name='rounds_amount',
            field=models.PositiveIntegerField(default=3, verbose_name='Кол-во раундов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
