# Generated by Django 4.0.1 on 2022-01-09 20:58

import djongo.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_id',
            field=djongo.models.fields.ObjectIdField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
