# Generated by Django 4.0.1 on 2022-02-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_gymnastic_value_alter_set_rounds_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=32, verbose_name='Алиас'),
            preserve_default=False,
        ),
    ]
