# Generated by Django 4.0.1 on 2022-01-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
